# Generated by Django 4.2.6 on 2023-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], null=True),
        ),
    ]
