# Generated by Django 4.2.6 on 2023-10-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], null=True),
        ),
    ]
